/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Calibri_19_Bold.c                                     *
* Font:        Calibri                                               *
* Height:      19                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  36                                           *
* Edit/Delete/Bottom    at character 0xB1 (177)                      *
* Edit/Delete/Bottom    at character 0xB1 (177)                      *
* Edit/Delete/Bottom    at character 0xB1 (177)                      *
* Edit/Delete/Bottom    at character 0xB1 (177)                      *
* Edit/Delete/Bottom    at character 0xB1 (177)                      *
* Edit/Delete/Bottom    at character 0xB1 (177)                      *
* Edit/Delete/Bottom    at character 0xB1 (177)                      *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x20 (32)                                     *
* Character disabled:  0x40 (64)                                     *
* Character disabled:  0x5B (91)                                     *
* Character disabled:  0x5C (92)                                     *
* Character disabled:  0x5D (93)                                     *
* Character disabled:  0x5E (94)                                     *
* Character disabled:  0x5F (95)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCalibri_19_Bold;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0020[ 19] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0041[ 57] = { /* code 0041, LATIN CAPITAL LETTER A */
  ______XX,XXX_____,________,
  ______XX,XXXX____,________,
  _____XXX,XXXX____,________,
  _____XXX,_XXX____,________,
  _____XXX,_XXXX___,________,
  _____XXX,_XXXX___,________,
  ____XXXX,__XXX___,________,
  ____XXX_,__XXXX__,________,
  ____XXX_,__XXXX__,________,
  ___XXXX_,___XXXX_,________,
  ___XXX__,___XXXX_,________,
  ___XXX__,___XXXX_,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,________,
  _XXXX___,_____XXX,X_______,
  _XXXX___,_____XXX,X_______,
  _XXX____,_____XXX,XX______,
  XXXX____,______XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0042[ 57] = { /* code 0042, LATIN CAPITAL LETTER B */
  __XXXXXX,XXXX____,________,
  __XXXXXX,XXXXXX__,________,
  __XXXXXX,XXXXXX__,________,
  __XXXX__,__XXXXX_,________,
  __XXXX__,___XXXX_,________,
  __XXXX__,___XXXX_,________,
  __XXXX__,___XXXX_,________,
  __XXXX__,__XXXX__,________,
  __XXXXXX,XXXXX___,________,
  __XXXXXX,XXXXXX__,________,
  __XXXXXX,XXXXXXX_,________,
  __XXXX__,___XXXXX,________,
  __XXXX__,____XXXX,________,
  __XXXX__,____XXXX,________,
  __XXXX__,____XXXX,________,
  __XXXX__,___XXXXX,________,
  __XXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXX__,________,
  __XXXXXX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0043[ 38] = { /* code 0043, LATIN CAPITAL LETTER C */
  _______X,XXXX____,
  _____XXX,XXXXXX__,
  ___XXXXX,XXXXXXX_,
  ___XXXXX,____XXX_,
  __XXXXX_,______X_,
  __XXXX__,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  __XXXX__,________,
  __XXXX__,______X_,
  __XXXXXX,____XXX_,
  ___XXXXX,XXXXXXX_,
  ____XXXX,XXXXXX__,
  ______XX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0044[ 57] = { /* code 0044, LATIN CAPITAL LETTER D */
  __XXXXXX,XXXX____,________,
  __XXXXXX,XXXXXX__,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXX__,___XXXXX,________,
  __XXXX__,____XXXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,____XXXX,X_______,
  __XXXX__,___XXXXX,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXX__,________,
  __XXXXXX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0045[ 38] = { /* code 0045, LATIN CAPITAL LETTER E */
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0046[ 38] = { /* code 0046, LATIN CAPITAL LETTER F */
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0047[ 57] = { /* code 0047, LATIN CAPITAL LETTER G */
  _______X,XXXXXX__,________,
  _____XXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,X_______,
  ___XXXXX,______XX,X_______,
  __XXXXX_,________,X_______,
  __XXXX__,________,________,
  _XXXXX__,________,________,
  _XXXX___,________,________,
  _XXXX___,_XXXXXXX,X_______,
  _XXXX___,_XXXXXXX,X_______,
  _XXXX___,_XXXXXXX,X_______,
  _XXXX___,_____XXX,X_______,
  _XXXX___,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXXX_,_____XXX,X_______,
  ___XXXXX,_____XXX,X_______,
  ____XXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,X_______,
  _______X,XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0048[ 57] = { /* code 0048, LATIN CAPITAL LETTER H */
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0049[ 19] = { /* code 0049, LATIN CAPITAL LETTER I */
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_004A[ 38] = { /* code 004A, LATIN CAPITAL LETTER J */
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  X___XXXX,________,
  XXXXXXXX,________,
  XXXXXXX_,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_004B[ 38] = { /* code 004B, LATIN CAPITAL LETTER K */
  __XXXX__,____XXXX,
  __XXXX__,___XXXXX,
  __XXXX__,___XXXX_,
  __XXXX__,__XXXX__,
  __XXXX__,_XXXX___,
  __XXXX__,XXXXX___,
  __XXXX__,XXXX____,
  __XXXX_X,XXX_____,
  __XXXXXX,XX______,
  __XXXXXX,XXX_____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,___XXXX_,
  __XXXX__,___XXXXX,
  __XXXX__,____XXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_004C[ 38] = { /* code 004C, LATIN CAPITAL LETTER L */
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_004D[ 76] = { /* code 004D, LATIN CAPITAL LETTER M */
  __XXXXXX,________,__XXXXXX,________,
  __XXXXXX,X_______,_XXXXXXX,________,
  __XXXXXX,X_______,_XXXXXXX,________,
  __XXXXXX,XX______,XXXXXXXX,________,
  __XXXX_X,XX______,XXX_XXXX,________,
  __XXXX_X,XX______,XXX_XXXX,________,
  __XXXX_X,XXX____X,XXX_XXXX,________,
  __XXXX_X,XXX____X,XX__XXXX,________,
  __XXXX__,XXX____X,XX__XXXX,________,
  __XXXX__,XXXX__XX,XX__XXXX,________,
  __XXXX__,XXXX__XX,X___XXXX,________,
  __XXXX__,_XXX__XX,X___XXXX,________,
  __XXXX__,_XXXXXXX,X___XXXX,________,
  __XXXX__,_XXXXXXX,____XXXX,________,
  __XXXX__,__XXXXXX,____XXXX,________,
  __XXXX__,__XXXXXX,____XXXX,________,
  __XXXX__,__XXXXX_,____XXXX,________,
  __XXXX__,___XXXX_,____XXXX,________,
  __XXXX__,___XXXX_,____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_004E[ 57] = { /* code 004E, LATIN CAPITAL LETTER N */
  __XXXXX_,_______X,XX______,
  __XXXXXX,_______X,XX______,
  __XXXXXX,_______X,XX______,
  __XXXXXX,X______X,XX______,
  __XXXXXX,X______X,XX______,
  __XXX_XX,XX_____X,XX______,
  __XXX_XX,XX_____X,XX______,
  __XXX__X,XXX____X,XX______,
  __XXX__X,XXXX___X,XX______,
  __XXX___,XXXX___X,XX______,
  __XXX___,_XXXX__X,XX______,
  __XXX___,_XXXX__X,XX______,
  __XXX___,__XXXX_X,XX______,
  __XXX___,___XXX_X,XX______,
  __XXX___,___XXXXX,XX______,
  __XXX___,____XXXX,XX______,
  __XXX___,____XXXX,XX______,
  __XXX___,_____XXX,XX______,
  __XXX___,______XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_004F[ 57] = { /* code 004F, LATIN CAPITAL LETTER O */
  _______X,XXXXXX__,________,
  _____XXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,X_______,
  ___XXXXX,____XXXX,XX______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXXX_,____XXXX,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXX_,________,
  ______XX,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0050[ 38] = { /* code 0050, LATIN CAPITAL LETTER P */
  __XXXXXX,XXX_____,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXXX__,
  __XXXX__,__XXXXX_,
  __XXXX__,___XXXX_,
  __XXXX__,___XXXX_,
  __XXXX__,___XXXX_,
  __XXXX__,___XXXX_,
  __XXXX__,__XXXX__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXX_____,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0051[ 57] = { /* code 0051, LATIN CAPITAL LETTER Q */
  _______X,XXXXXX__,________,
  _____XXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,X_______,
  ___XXXXX,____XXXX,XX______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXXX_,____XXXX,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XX______,
  ______XX,XXXXX_XX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0052[ 57] = { /* code 0052, LATIN CAPITAL LETTER R */
  __XXXXXX,XXXX____,________,
  __XXXXXX,XXXXXX__,________,
  __XXXXXX,XXXXXX__,________,
  __XXXX__,__XXXXX_,________,
  __XXXX__,___XXXX_,________,
  __XXXX__,___XXXX_,________,
  __XXXX__,___XXXX_,________,
  __XXXX__,__XXXX__,________,
  __XXXXXX,XXXXXX__,________,
  __XXXXXX,XXXX____,________,
  __XXXXXX,XXXX____,________,
  __XXXX__,_XXXX___,________,
  __XXXX__,__XXXX__,________,
  __XXXX__,__XXXX__,________,
  __XXXX__,___XXXX_,________,
  __XXXX__,___XXXX_,________,
  __XXXX__,___XXXX_,________,
  __XXXX__,____XXXX,________,
  __XXXX__,____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0053[ 38] = { /* code 0053, LATIN CAPITAL LETTER S */
  ____XXXX,XXX_____,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXX____,
  _XXXXX__,__XX____,
  _XXXX___,________,
  _XXXX___,________,
  _XXXXX__,________,
  _XXXXXXX,________,
  __XXXXXX,XX______,
  ___XXXXX,XXX_____,
  _____XXX,XXXX____,
  _______X,XXXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  _X______,_XXXX___,
  _XXX____,XXXXX___,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0054[ 38] = { /* code 0054, LATIN CAPITAL LETTER T */
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0055[ 57] = { /* code 0055, LATIN CAPITAL LETTER U */
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXXX_,____XXXX,X_______,
  ___XXXXX,___XXXXX,________,
  ___XXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXX_,________,
  ______XX,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0056[ 57] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXX____,______XX,XX______,
  XXXXX___,_____XXX,XX______,
  _XXXX___,_____XXX,X_______,
  _XXXX___,_____XXX,X_______,
  __XXXX__,____XXXX,X_______,
  __XXXX__,____XXXX,________,
  __XXXX__,____XXXX,________,
  ___XXXX_,____XXXX,________,
  ___XXXX_,___XXXX_,________,
  ___XXXXX,___XXXX_,________,
  ____XXXX,___XXXX_,________,
  ____XXXX,___XXX__,________,
  ____XXXX,X_XXXX__,________,
  _____XXX,X_XXX___,________,
  _____XXX,X_XXX___,________,
  ______XX,XXXXX___,________,
  ______XX,XXXX____,________,
  ______XX,XXXX____,________,
  _______X,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0057[ 76] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXXX____,___XXXXX,_______X,XXX_____,
  XXXXX___,___XXXXX,______XX,XXX_____,
  _XXXX___,___XXXXX,______XX,XX______,
  _XXXX___,___XXXXX,X_____XX,XX______,
  _XXXX___,__XXXXXX,X_____XX,XX______,
  __XXX___,__XXXXXX,X_____XX,X_______,
  __XXXX__,__XXX_XX,X____XXX,X_______,
  __XXXX__,__XXX_XX,XX___XXX,X_______,
  __XXXX__,_XXXX_XX,XX___XXX,X_______,
  ___XXX__,_XXXX_XX,XX___XXX,________,
  ___XXXX_,_XXX___X,XX___XXX,________,
  ___XXXX_,XXXX___X,XXX_XXXX,________,
  ___XXXX_,XXXX___X,XXX_XXXX,________,
  ____XXX_,XXXX___X,XXX_XXX_,________,
  ____XXX_,XXX_____,XXX_XXX_,________,
  ____XXXX,XXX_____,XXXXXXX_,________,
  ____XXXX,XXX_____,XXXXXX__,________,
  _____XXX,XX______,XXXXXX__,________,
  _____XXX,XX______,_XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0058[ 57] = { /* code 0058, LATIN CAPITAL LETTER X */
  __XXXX__,___XXXX_,________,
  __XXXX__,___XXXX_,________,
  __XXXXX_,__XXXXX_,________,
  ___XXXX_,__XXXX__,________,
  ____XXXX,_XXXX___,________,
  ____XXXX,_XXXX___,________,
  _____XXX,_XXX____,________,
  _____XXX,XXXX____,________,
  ______XX,XXX_____,________,
  ______XX,XXX_____,________,
  _____XXX,XXXX____,________,
  _____XXX,XXXX____,________,
  ____XXXX,_XXXX___,________,
  ____XXXX,_XXXX___,________,
  ___XXXX_,__XXXX__,________,
  ___XXXX_,__XXXX__,________,
  __XXXX__,___XXXX_,________,
  _XXXXX__,___XXXXX,________,
  _XXXX___,____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_0059[ 38] = { /* code 0059, LATIN CAPITAL LETTER Y */
  _XXXX___,___XXXX_,
  _XXXX___,___XXXX_,
  _XXXXX__,__XXXXX_,
  __XXXX__,__XXXX__,
  __XXXXX_,_XXXXX__,
  ___XXXX_,_XXXX___,
  ___XXXX_,_XXXX___,
  ____XXXX,XXXX____,
  ____XXXX,XXXX____,
  _____XXX,XXX_____,
  _____XXX,XXX_____,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_19_Bold_005A[ 38] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  ________,__XXXX__,
  ________,_XXXX___,
  ________,XXXX____,
  ________,XXXX____,
  _______X,XXX_____,
  ______XX,XX______,
  ______XX,X_______,
  _____XXX,X_______,
  ____XXXX,________,
  ____XXX_,________,
  ___XXXX_,________,
  __XXXX__,________,
  __XXX___,________,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontCalibri_19_Bold_CharInfo[27] = {
   {   7,   7,  1, acGUI_FontCalibri_19_Bold_0020 } /* code 0020 */
  ,{  18,  18,  3, acGUI_FontCalibri_19_Bold_0041 } /* code 0041 */
  ,{  17,  17,  3, acGUI_FontCalibri_19_Bold_0042 } /* code 0042 */
  ,{  16,  16,  2, acGUI_FontCalibri_19_Bold_0043 } /* code 0043 */
  ,{  19,  19,  3, acGUI_FontCalibri_19_Bold_0044 } /* code 0044 */
  ,{  15,  15,  2, acGUI_FontCalibri_19_Bold_0045 } /* code 0045 */
  ,{  14,  14,  2, acGUI_FontCalibri_19_Bold_0046 } /* code 0046 */
  ,{  19,  19,  3, acGUI_FontCalibri_19_Bold_0047 } /* code 0047 */
  ,{  19,  19,  3, acGUI_FontCalibri_19_Bold_0048 } /* code 0048 */
  ,{   8,   8,  1, acGUI_FontCalibri_19_Bold_0049 } /* code 0049 */
  ,{  10,  10,  2, acGUI_FontCalibri_19_Bold_004A } /* code 004A */
  ,{  16,  16,  2, acGUI_FontCalibri_19_Bold_004B } /* code 004B */
  ,{  13,  13,  2, acGUI_FontCalibri_19_Bold_004C } /* code 004C */
  ,{  26,  26,  4, acGUI_FontCalibri_19_Bold_004D } /* code 004D */
  ,{  20,  20,  3, acGUI_FontCalibri_19_Bold_004E } /* code 004E */
  ,{  20,  20,  3, acGUI_FontCalibri_19_Bold_004F } /* code 004F */
  ,{  16,  16,  2, acGUI_FontCalibri_19_Bold_0050 } /* code 0050 */
  ,{  21,  21,  3, acGUI_FontCalibri_19_Bold_0051 } /* code 0051 */
  ,{  17,  17,  3, acGUI_FontCalibri_19_Bold_0052 } /* code 0052 */
  ,{  14,  14,  2, acGUI_FontCalibri_19_Bold_0053 } /* code 0053 */
  ,{  15,  15,  2, acGUI_FontCalibri_19_Bold_0054 } /* code 0054 */
  ,{  20,  20,  3, acGUI_FontCalibri_19_Bold_0055 } /* code 0055 */
  ,{  18,  18,  3, acGUI_FontCalibri_19_Bold_0056 } /* code 0056 */
  ,{  27,  27,  4, acGUI_FontCalibri_19_Bold_0057 } /* code 0057 */
  ,{  17,  17,  3, acGUI_FontCalibri_19_Bold_0058 } /* code 0058 */
  ,{  16,  16,  2, acGUI_FontCalibri_19_Bold_0059 } /* code 0059 */
  ,{  14,  14,  2, acGUI_FontCalibri_19_Bold_005A } /* code 005A */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_19_Bold_Prop2 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontCalibri_19_Bold_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_19_Bold_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontCalibri_19_Bold_CharInfo[  0] /* address of first character */
  ,&GUI_FontCalibri_19_Bold_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCalibri_19_Bold = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,19 /* height of font  */
  ,19 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCalibri_19_Bold_Prop1}
  ,19 /* Baseline */
  ,14 /* Height of lowercase characters */
  ,19 /* Height of capital characters */
};

