/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Calibri_15_Bold.c                                     *
* Font:        Calibri                                               *
* Height:      15                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  29                                           *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x20 (32)                                     *
* Character disabled:  0x40 (64)                                     *
* Character disabled:  0x3A (58)                                     *
* Character disabled:  0x3B (59)                                     *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3D (61)                                     *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3F (63)                                     *
* Character disabled:  0x5B (91)                                     *
* Character disabled:  0x5C (92)                                     *
* Character disabled:  0x5D (93)                                     *
* Character disabled:  0x5E (94)                                     *
* Character disabled:  0x5F (95)                                     *
* Character enabled:   0x25 (37)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCalibri_15_Bold;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0020[ 15] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0025[ 45] = { /* code 0025, PERCENT SIGN */
  __XXXXXX,____XX__,________,
  _XX___XX,____XX__,________,
  _XX___XX,___XX___,________,
  _XX___XX,__XX____,________,
  _XX___XX,_XX_____,________,
  _XXXXXX_,_XX_____,________,
  __XXXX__,XX______,________,
  _______X,X___XXXX,________,
  ______XX,___XXXXX,X_______,
  ______XX,__XX___X,X_______,
  _____XX_,__XX___X,X_______,
  ____XX__,__XX___X,X_______,
  ___XX___,__XX___X,X_______,
  ___XX___,__XXXXXX,________,
  __XX____,___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0030[ 30] = { /* code 0030, DIGIT ZERO */
  ____XXXX,X_______,
  ___XXXXX,XXX_____,
  __XXX___,XXX_____,
  __XX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XX_____,
  __XXX___,XXX_____,
  __XXXXXX,XX______,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0031[ 30] = { /* code 0031, DIGIT ONE */
  _____XXX,________,
  ___XXXXX,________,
  __XXXXXX,________,
  __XX_XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0032[ 30] = { /* code 0032, DIGIT TWO */
  ___XXXXX,________,
  _XXXXXXX,X_______,
  _XX___XX,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  ____XXX_,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0033[ 30] = { /* code 0033, DIGIT THREE */
  __XXXXXX,________,
  _XXXXXXX,X_______,
  _XX___XX,XX______,
  _______X,XX______,
  _______X,XX______,
  ______XX,X_______,
  __XXXXXX,________,
  __XXXXXX,X_______,
  _______X,XX______,
  ________,XXX_____,
  ________,XXX_____,
  ________,XXX_____,
  _XX____X,XX______,
  _XXXXXXX,XX______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0034[ 30] = { /* code 0034, DIGIT FOUR */
  _____XXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XX_XX,X_______,
  ___XX_XX,X_______,
  __XXX_XX,X_______,
  __XX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  XXX___XX,X_______,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0035[ 30] = { /* code 0035, DIGIT FIVE */
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXXXXX,X_______,
  __XXXXXX,XX______,
  _______X,XXX_____,
  ________,XXX_____,
  ________,XXX_____,
  ________,XXX_____,
  _X_____X,XX______,
  _XXXXXXX,XX______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0036[ 30] = { /* code 0036, DIGIT SIX */
  ____XXXX,XX______,
  ___XXXXX,XX______,
  __XXXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XXX____,________,
  _XXX_XXX,X_______,
  _XXXXXXX,XX______,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  __XXX__X,XX______,
  __XXXXXX,XX______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0037[ 30] = { /* code 0037, DIGIT SEVEN */
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,XXX_____,
  _______X,XX______,
  _______X,XX______,
  _______X,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0038[ 30] = { /* code 0038, DIGIT EIGHT */
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXX___,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXXX__,XXX_____,
  __XXXXXX,XX______,
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXX___,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXX___,XXXX____,
  __XXXXXX,XXX_____,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0039[ 30] = { /* code 0039, DIGIT NINE */
  ____XXXX,X_______,
  __XXXXXX,XX______,
  _XXXX__X,XX______,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXXX___,XXX_____,
  __XXXXXX,XXX_____,
  ___XXXX_,XXX_____,
  ________,XXX_____,
  ________,XXX_____,
  _______X,XX______,
  __X___XX,XX______,
  __XXXXXX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0041[ 30] = { /* code 0041, LATIN CAPITAL LETTER A */
  ______XX,XX______,
  _____XXX,XX______,
  _____XX_,XX______,
  ____XXX_,XXX_____,
  ____XXX_,XXX_____,
  ____XX__,XXXX____,
  ___XXX__,_XXX____,
  ___XXX__,_XXX____,
  ___XX___,_XXXX___,
  __XXX___,__XXX___,
  __XXXXXX,XXXXX___,
  _XXXXXXX,XXXXXX__,
  _XXX____,___XXX__,
  _XXX____,___XXX__,
  XXX_____,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0042[ 30] = { /* code 0042, LATIN CAPITAL LETTER B */
  __XXXXXX,X_______,
  __XXXXXX,XX______,
  __XXX___,XXX_____,
  __XXX___,XXX_____,
  __XXX___,XXX_____,
  __XXX___,XXX_____,
  __XXXXXX,X_______,
  __XXXXXX,XXX_____,
  __XXX___,XXXX____,
  __XXX___,_XXX____,
  __XXX___,_XXX____,
  __XXX___,_XXX____,
  __XXX___,XXXX____,
  __XXXXXX,XXX_____,
  __XXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0043[ 30] = { /* code 0043, LATIN CAPITAL LETTER C */
  _____XXX,XXX_____,
  ___XXXXX,XXXX____,
  ___XXX__,__XX____,
  __XXX___,________,
  _XXXX___,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  __XXX___,________,
  __XXXX__,__XX____,
  ___XXXXX,XXXX____,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0044[ 30] = { /* code 0044, LATIN CAPITAL LETTER D */
  __XXXXXX,XXX_____,
  __XXXXXX,XXXXX___,
  __XXX___,_XXXXX__,
  __XXX___,___XXX__,
  __XXX___,___XXXX_,
  __XXX___,____XXX_,
  __XXX___,____XXX_,
  __XXX___,____XXX_,
  __XXX___,____XXX_,
  __XXX___,____XXX_,
  __XXX___,___XXXX_,
  __XXX___,___XXX__,
  __XXX___,_XXXX___,
  __XXXXXX,XXXX____,
  __XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0045[ 30] = { /* code 0045, LATIN CAPITAL LETTER E */
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0046[ 30] = { /* code 0046, LATIN CAPITAL LETTER F */
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0047[ 30] = { /* code 0047, LATIN CAPITAL LETTER G */
  ______XX,XXXXX___,
  ____XXXX,XXXXXX__,
  ___XXXX_,____XX__,
  __XXX___,________,
  __XXX___,________,
  _XXX____,________,
  _XXX___X,XXXXXX__,
  _XXX___X,XXXXXX__,
  _XXX____,___XXX__,
  _XXX____,___XXX__,
  _XXXX___,___XXX__,
  __XXX___,___XXX__,
  ___XXXX_,___XXX__,
  ____XXXX,XXXXXX__,
  ______XX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0048[ 30] = { /* code 0048, LATIN CAPITAL LETTER H */
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0049[ 15] = { /* code 0049, LATIN CAPITAL LETTER I */
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_004A[ 15] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  XXXXX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_004B[ 30] = { /* code 004B, LATIN CAPITAL LETTER K */
  __XXX___,__XXX___,
  __XXX___,_XXX____,
  __XXX___,XXXX____,
  __XXX___,XXX_____,
  __XXX__X,XX______,
  __XXX_XX,X_______,
  __XXXXXX,________,
  __XXXXXX,________,
  __XXX_XX,X_______,
  __XXX_XX,XX______,
  __XXX__X,XX______,
  __XXX___,XXX_____,
  __XXX___,_XXX____,
  __XXX___,_XXXX___,
  __XXX___,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_004C[ 30] = { /* code 004C, LATIN CAPITAL LETTER L */
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXXXXX,XX______,
  __XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_004D[ 45] = { /* code 004D, LATIN CAPITAL LETTER M */
  __XXXXX_,_______X,XXXX____,
  __XXXXXX,_______X,XXXX____,
  __XXXXXX,______XX,XXXX____,
  __XXX_XX,______XX,_XXX____,
  __XXX_XX,X____XXX,_XXX____,
  __XXX_XX,X____XXX,_XXX____,
  __XXX__X,X____XX_,_XXX____,
  __XXX__X,XX__XXX_,_XXX____,
  __XXX__X,XX__XXX_,_XXX____,
  __XXX___,XXXXXX__,_XXX____,
  __XXX___,XXXXXX__,_XXX____,
  __XXX___,XXXXXX__,_XXX____,
  __XXX___,_XXXX___,_XXX____,
  __XXX___,_XXXX___,_XXX____,
  __XXX___,_XXX____,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_004E[ 30] = { /* code 004E, LATIN CAPITAL LETTER N */
  __XXXXX_,____XXX_,
  __XXXXX_,____XXX_,
  __XXXXXX,____XXX_,
  __XXXXXX,____XXX_,
  __XXX_XX,X___XXX_,
  __XXX_XX,X___XXX_,
  __XXX__X,XX__XXX_,
  __XXX__X,XX__XXX_,
  __XXX___,XXX_XXX_,
  __XXX___,XXX_XXX_,
  __XXX___,_XX_XXX_,
  __XXX___,_XXXXXX_,
  __XXX___,__XXXXX_,
  __XXX___,__XXXXX_,
  __XXX___,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_004F[ 30] = { /* code 004F, LATIN CAPITAL LETTER O */
  _____XXX,XXX_____,
  ___XXXXX,XXXXX___,
  __XXXX__,__XXXX__,
  __XXX___,___XXX__,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  __XXX___,___XXX__,
  __XXXX__,__XXXX__,
  ___XXXXX,XXXXX___,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0050[ 30] = { /* code 0050, LATIN CAPITAL LETTER P */
  __XXXXXX,X_______,
  __XXXXXX,XXX_____,
  __XXX___,XXXX____,
  __XXX___,_XXX____,
  __XXX___,_XXX____,
  __XXX___,_XXX____,
  __XXX___,_XXX____,
  __XXX___,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,X_______,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0051[ 30] = { /* code 0051, LATIN CAPITAL LETTER Q */
  _____XXX,XXX_____,
  ___XXXXX,XXXXX___,
  __XXXX__,__XXXX__,
  __XXX___,___XXX__,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  _XXX____,____XXX_,
  __XXX___,___XXX__,
  __XXXX__,__XXXX__,
  ___XXXXX,XXXXXX__,
  _____XXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0052[ 30] = { /* code 0052, LATIN CAPITAL LETTER R */
  __XXXXXX,XX______,
  __XXXXXX,XXX_____,
  __XXX___,XXXX____,
  __XXX___,_XXX____,
  __XXX___,_XXX____,
  __XXX___,_XXX____,
  __XXX___,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,XX______,
  __XXX__X,XXX_____,
  __XXX___,XXX_____,
  __XXX___,_XXX____,
  __XXX___,_XXX____,
  __XXX___,__XXX___,
  __XXX___,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0053[ 30] = { /* code 0053, LATIN CAPITAL LETTER S */
  ___XXXXX,X_______,
  __XXXXXX,XX______,
  _XXXX___,XX______,
  _XXX____,________,
  _XXX____,________,
  _XXXX___,________,
  __XXXXXX,________,
  ___XXXXX,XX______,
  _____XXX,XX______,
  _______X,XXX_____,
  ________,XXX_____,
  ________,XXX_____,
  _XX____X,XX______,
  _XXXXXXX,XX______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0054[ 30] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0055[ 30] = { /* code 0055, LATIN CAPITAL LETTER U */
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  __XXX___,___XXX__,
  ___XXX__,__XXX___,
  ___XXXXX,XXXX____,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0056[ 30] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXX_____,___XXX__,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXXX___,__XXX___,
  __XXX___,_XXX____,
  __XXX___,_XXX____,
  __XXXX__,_XXX____,
  ___XXX__,_XX_____,
  ___XXX__,XXX_____,
  ___XXXX_,XXX_____,
  ____XXX_,XXX_____,
  ____XXX_,XX______,
  ____XXXX,XX______,
  _____XXX,XX______,
  _____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0057[ 45] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXX_____,_XXX____,__XXX___,
  _XXX____,_XXXX___,_XXX____,
  _XXX____,_XXXX___,_XXX____,
  _XXX____,XXXXX___,_XXX____,
  _XXXX___,XXXXXX__,_XXX____,
  __XXX___,XX_XXX__,_XX_____,
  __XXX___,XX_XXX__,XXX_____,
  __XXX___,XX_XXX__,XXX_____,
  ___XXX_X,XX__XXX_,XXX_____,
  ___XXX_X,X___XXX_,XX______,
  ___XXX_X,X___XXX_,XX______,
  ___XXX_X,X___XXX_,XX______,
  ____XXXX,X____XXX,XX______,
  ____XXXX,X____XXX,XX______,
  ____XXXX,_____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0058[ 30] = { /* code 0058, LATIN CAPITAL LETTER X */
  _XXX____,_XXX____,
  _XXXX___,XXXX____,
  __XXX___,XXX_____,
  __XXXX_X,XXX_____,
  ___XXX_X,XX______,
  ___XXXXX,XX______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XXX_X,XX______,
  __XXXX_X,XXX_____,
  __XXX___,XXX_____,
  _XXXX___,XXXX____,
  _XXX____,_XXX____,
  XXXX____,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_0059[ 30] = { /* code 0059, LATIN CAPITAL LETTER Y */
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  __XXX___,XXX_____,
  __XXX___,XXX_____,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_15_Bold_005A[ 30] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,XXX_____,
  _______X,XX______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontCalibri_15_Bold_CharInfo[38] = {
   {   5,   5,  1, acGUI_FontCalibri_15_Bold_0020 } /* code 0020 */
  ,{  18,  18,  3, acGUI_FontCalibri_15_Bold_0025 } /* code 0025 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0030 } /* code 0030 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0031 } /* code 0031 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0032 } /* code 0032 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0033 } /* code 0033 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0034 } /* code 0034 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0035 } /* code 0035 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0036 } /* code 0036 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0037 } /* code 0037 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0038 } /* code 0038 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0039 } /* code 0039 */
  ,{  15,  15,  2, acGUI_FontCalibri_15_Bold_0041 } /* code 0041 */
  ,{  13,  13,  2, acGUI_FontCalibri_15_Bold_0042 } /* code 0042 */
  ,{  13,  13,  2, acGUI_FontCalibri_15_Bold_0043 } /* code 0043 */
  ,{  15,  15,  2, acGUI_FontCalibri_15_Bold_0044 } /* code 0044 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0045 } /* code 0045 */
  ,{  11,  11,  2, acGUI_FontCalibri_15_Bold_0046 } /* code 0046 */
  ,{  15,  15,  2, acGUI_FontCalibri_15_Bold_0047 } /* code 0047 */
  ,{  15,  15,  2, acGUI_FontCalibri_15_Bold_0048 } /* code 0048 */
  ,{   6,   6,  1, acGUI_FontCalibri_15_Bold_0049 } /* code 0049 */
  ,{   8,   8,  1, acGUI_FontCalibri_15_Bold_004A } /* code 004A */
  ,{  13,  13,  2, acGUI_FontCalibri_15_Bold_004B } /* code 004B */
  ,{  10,  10,  2, acGUI_FontCalibri_15_Bold_004C } /* code 004C */
  ,{  21,  21,  3, acGUI_FontCalibri_15_Bold_004D } /* code 004D */
  ,{  16,  16,  2, acGUI_FontCalibri_15_Bold_004E } /* code 004E */
  ,{  16,  16,  2, acGUI_FontCalibri_15_Bold_004F } /* code 004F */
  ,{  13,  13,  2, acGUI_FontCalibri_15_Bold_0050 } /* code 0050 */
  ,{  16,  16,  2, acGUI_FontCalibri_15_Bold_0051 } /* code 0051 */
  ,{  14,  14,  2, acGUI_FontCalibri_15_Bold_0052 } /* code 0052 */
  ,{  11,  11,  2, acGUI_FontCalibri_15_Bold_0053 } /* code 0053 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0054 } /* code 0054 */
  ,{  16,  16,  2, acGUI_FontCalibri_15_Bold_0055 } /* code 0055 */
  ,{  14,  14,  2, acGUI_FontCalibri_15_Bold_0056 } /* code 0056 */
  ,{  22,  22,  3, acGUI_FontCalibri_15_Bold_0057 } /* code 0057 */
  ,{  13,  13,  2, acGUI_FontCalibri_15_Bold_0058 } /* code 0058 */
  ,{  12,  12,  2, acGUI_FontCalibri_15_Bold_0059 } /* code 0059 */
  ,{  11,  11,  2, acGUI_FontCalibri_15_Bold_005A } /* code 005A */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_15_Bold_Prop4 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontCalibri_15_Bold_CharInfo[ 12] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_15_Bold_Prop3 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontCalibri_15_Bold_CharInfo[  2] /* address of first character */
  ,&GUI_FontCalibri_15_Bold_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_15_Bold_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontCalibri_15_Bold_CharInfo[  1] /* address of first character */
  ,&GUI_FontCalibri_15_Bold_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_15_Bold_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontCalibri_15_Bold_CharInfo[  0] /* address of first character */
  ,&GUI_FontCalibri_15_Bold_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCalibri_15_Bold = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,15 /* height of font  */
  ,15 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCalibri_15_Bold_Prop1}
  ,15 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,15 /* Height of capital characters */
};

