/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Calibri_9_Bold.c                                      *
* Font:        Calibri                                               *
* Height:      9                                                     *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  18                                           *
* Edit/Delete/Top       at character 0x31 (49)                       *
* Edit/Delete/Top       at character 0x31 (49)                       *
* Edit/Delete/Top       at character 0x31 (49)                       *
* Edit/Delete/Top       at character 0x31 (49)                       *
* Edit/Delete/Top       at character 0x31 (49)                       *
* Edit/Delete/Bottom    at character 0x31 (49)                       *
* Edit/Delete/Bottom    at character 0x31 (49)                       *
* Edit/Delete/Bottom    at character 0x31 (49)                       *
* Edit/Delete/Bottom    at character 0x31 (49)                       *
* Character disabled:  0x31 (49)                                     *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character enabled:   0x32 (50)                                     *
* Character enabled:   0x35 (53)                                     *
* Character disabled:  0x35 (53)                                     *
* Character enabled:   0x2E (46)                                     *
* Character enabled:   0x35 (53)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCalibri_9_Bold;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_9_Bold_002E[  9] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_9_Bold_0030[  9] = { /* code 0030, DIGIT ZERO */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_9_Bold_0031[  9] = { /* code 0031, DIGIT ONE */
  __XX____,
  _XXX____,
  X_XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_9_Bold_0032[  9] = { /* code 0032, DIGIT TWO */
  _XXXX___,
  X___XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XX______,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_9_Bold_0035[  9] = { /* code 0035, DIGIT FIVE */
  XXXXXX__,
  XX______,
  XX______,
  XXXXX___,
  ____XX__,
  ____XX__,
  ____XX__,
  X___XX__,
  _XXXX___};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontCalibri_9_Bold_CharInfo[5] = {
   {   4,   4,  1, acGUI_FontCalibri_9_Bold_002E } /* code 002E */
  ,{   7,   7,  1, acGUI_FontCalibri_9_Bold_0030 } /* code 0030 */
  ,{   7,   7,  1, acGUI_FontCalibri_9_Bold_0031 } /* code 0031 */
  ,{   7,   7,  1, acGUI_FontCalibri_9_Bold_0032 } /* code 0032 */
  ,{   7,   7,  1, acGUI_FontCalibri_9_Bold_0035 } /* code 0035 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_9_Bold_Prop3 = {
   0x0035 /* first character */
  ,0x0035 /* last character  */
  ,&GUI_FontCalibri_9_Bold_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_9_Bold_Prop2 = {
   0x0030 /* first character */
  ,0x0032 /* last character  */
  ,&GUI_FontCalibri_9_Bold_CharInfo[  1] /* address of first character */
  ,&GUI_FontCalibri_9_Bold_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_9_Bold_Prop1 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontCalibri_9_Bold_CharInfo[  0] /* address of first character */
  ,&GUI_FontCalibri_9_Bold_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCalibri_9_Bold = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,9 /* height of font  */
  ,9 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCalibri_9_Bold_Prop1}
  ,9 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,9 /* Height of capital characters */
};

