/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Calibri_13_Bold.c                                     *
* Font:        Calibri                                               *
* Height:      13                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  26                                           *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Top       at character 0x41 (65)                       *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x41 (65)                                     *
* Character disabled:  0x40 (64)                                     *
* Character enabled:   0x20 (32)                                     *
* Character disabled:  0x3A (58)                                     *
* Character disabled:  0x3B (59)                                     *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3D (61)                                     *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3F (63)                                     *
* Character disabled:  0x5B (91)                                     *
* Character disabled:  0x5C (92)                                     *
* Character disabled:  0x5D (93)                                     *
* Character disabled:  0x5E (94)                                     *
* Character disabled:  0x5F (95)                                     *
* Character enabled:   0x5F (95)                                     *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Edit/Delete/Bottom    at character 0x41 (65)                       *
* Character enabled:   0x25 (37)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCalibri_13_Bold;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0020[ 13] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0025[ 26] = { /* code 0025, PERCENT SIGN */
  XXXXXX__,__XX____,
  XX__XX__,__XX____,
  XX__XX__,_XX_____,
  XX__XX__,XX______,
  XXXXXX_X,XX______,
  _XXXX__X,X_______,
  ______XX,_XXXX___,
  _____XXX,XXXXXX__,
  _____XX_,XX__XX__,
  ____XX__,XX__XX__,
  ___XX___,XX__XX__,
  ___XX___,XXXXXX__,
  __XX____,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0030[ 26] = { /* code 0030, DIGIT ZERO */
  ___XXXXX,________,
  __XXXXXX,X_______,
  __XXX_XX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XXX_XX,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0031[ 26] = { /* code 0031, DIGIT ONE */
  ____XXX_,________,
  _XXXXXX_,________,
  _XX_XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0032[ 26] = { /* code 0032, DIGIT TWO */
  __XXXXX_,________,
  _XXXXXXX,________,
  _X____XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  ____XXX_,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0033[ 26] = { /* code 0033, DIGIT THREE */
  __XXXXXX,________,
  _XXXXXXX,X_______,
  _X____XX,X_______,
  ______XX,X_______,
  _____XXX,X_______,
  __XXXXX_,________,
  __XXXXXX,X_______,
  ______XX,XX______,
  _______X,XX______,
  _______X,XX______,
  _X____XX,XX______,
  _XXXXXXX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0034[ 26] = { /* code 0034, DIGIT FOUR */
  ____XXXX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  __XX_XXX,________,
  __XX_XXX,________,
  _XX__XXX,________,
  _XX__XXX,________,
  XX___XXX,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0035[ 26] = { /* code 0035, DIGIT FIVE */
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XXXXXX,________,
  __XXXXXX,X_______,
  ______XX,XX______,
  _______X,XX______,
  _______X,XX______,
  _X____XX,XX______,
  _XXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0036[ 26] = { /* code 0036, DIGIT SIX */
  ____XXXX,X_______,
  ___XXXXX,X_______,
  __XXX___,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,X_______,
  _XXXXXXX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX__X,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0037[ 26] = { /* code 0037, DIGIT SEVEN */
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _______X,XX______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXX___,________,
  __XXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0038[ 26] = { /* code 0038, DIGIT EIGHT */
  ___XXXXX,________,
  __XXXXXX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX__X,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  __XXX_XX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0039[ 26] = { /* code 0039, DIGIT NINE */
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX__XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXXXXX,XX______,
  __XXXXXX,XX______,
  _______X,XX______,
  _______X,X_______,
  ______XX,X_______,
  _XXXXXXX,________,
  _XXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0041[ 26] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XXX,________,
  ____XXXX,X_______,
  ____XX_X,X_______,
  ____XX_X,XX______,
  ___XXX_X,XX______,
  ___XX___,XX______,
  ___XX___,XXX_____,
  __XXX___,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXXX____,
  _XXX____,_XXX____,
  _XX_____,_XXX____,
  XXX_____,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0042[ 26] = { /* code 0042, LATIN CAPITAL LETTER B */
  _XXXXXXX,________,
  _XXXXXXX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXXXXX,________,
  _XXXXXXX,XX______,
  _XXX___X,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX___X,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0043[ 26] = { /* code 0043, LATIN CAPITAL LETTER C */
  _____XXX,XX______,
  ___XXXXX,XXX_____,
  __XXXX__,__X_____,
  __XXX___,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXX___,________,
  __XXXX__,__X_____,
  ___XXXXX,XXX_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0044[ 26] = { /* code 0044, LATIN CAPITAL LETTER D */
  _XXXXXXX,________,
  _XXXXXXX,XX______,
  _XXX___X,XXX_____,
  _XXX____,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,XXX_____,
  _XXX___X,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0045[ 26] = { /* code 0045, LATIN CAPITAL LETTER E */
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0046[ 26] = { /* code 0046, LATIN CAPITAL LETTER F */
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0047[ 26] = { /* code 0047, LATIN CAPITAL LETTER G */
  _____XXX,XXX_____,
  ___XXXXX,XXXX____,
  __XXXX__,___X____,
  __XXX___,________,
  _XXX____,________,
  _XXX____,________,
  _XXX___X,XXXX____,
  _XXX___X,XXXX____,
  _XXX____,_XXX____,
  __XXX___,_XXX____,
  __XXXX__,_XXX____,
  ___XXXXX,XXXX____,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0048[ 26] = { /* code 0048, LATIN CAPITAL LETTER H */
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0049[ 13] = { /* code 0049, LATIN CAPITAL LETTER I */
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_004A[ 13] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  XXXXXX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_004B[ 26] = { /* code 004B, LATIN CAPITAL LETTER K */
  _XXX____,XXX_____,
  _XXX___X,XX______,
  _XXX__XX,XX______,
  _XXX__XX,X_______,
  _XXX_XXX,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  _XXX_XXX,________,
  _XXX_XXX,X_______,
  _XXX__XX,X_______,
  _XXX___X,XX______,
  _XXX___X,XXX_____,
  _XXX____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_004C[ 26] = { /* code 004C, LATIN CAPITAL LETTER L */
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,________,
  _XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_004D[ 39] = { /* code 004D, LATIN CAPITAL LETTER M */
  _XXXXX__,___XXXXX,________,
  _XXXXX__,___XXXXX,________,
  _XXXXXX_,___XXXXX,________,
  _XXXXXX_,__XXXXXX,________,
  _XXX_XX_,__XX_XXX,________,
  _XXX_XX_,__XX_XXX,________,
  _XXX_XXX,_XXX_XXX,________,
  _XXX__XX,_XX__XXX,________,
  _XXX__XX,_XX__XXX,________,
  _XXX__XX,XXX__XXX,________,
  _XXX__XX,XX___XXX,________,
  _XXX___X,XX___XXX,________,
  _XXX___X,XX___XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_004E[ 26] = { /* code 004E, LATIN CAPITAL LETTER N */
  _XXX____,__XX____,
  _XXXX___,__XX____,
  _XXXXX__,__XX____,
  _XX_XX__,__XX____,
  _XX_XXX_,__XX____,
  _XX__XX_,__XX____,
  _XX__XXX,__XX____,
  _XX___XX,__XX____,
  _XX____X,X_XX____,
  _XX____X,X_XX____,
  _XX_____,XXXX____,
  _XX_____,XXXX____,
  _XX_____,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_004F[ 26] = { /* code 004F, LATIN CAPITAL LETTER O */
  _____XXX,XXX_____,
  ___XXXXX,XXXX____,
  __XXXX__,__XXX___,
  __XXX___,__XXXX__,
  _XXX____,___XXX__,
  _XXX____,___XXX__,
  _XXX____,___XXX__,
  _XXX____,___XXX__,
  _XXX____,___XXX__,
  _XXXX___,__XXX___,
  __XXX___,_XXXX___,
  ___XXXXX,XXXX____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0050[ 26] = { /* code 0050, LATIN CAPITAL LETTER P */
  _XXXXXXX,________,
  _XXXXXXX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX__XX,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0051[ 26] = { /* code 0051, LATIN CAPITAL LETTER Q */
  _____XXX,XXX_____,
  ___XXXXX,XXXX____,
  __XXXX__,__XXX___,
  __XXX___,__XXXX__,
  _XXX____,___XXX__,
  _XXX____,___XXX__,
  _XXX____,___XXX__,
  _XXX____,___XXX__,
  _XXX____,___XXX__,
  _XXXX___,__XXX___,
  __XXX___,_XXXX___,
  ___XXXXX,XXXX____,
  ____XXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0052[ 26] = { /* code 0052, LATIN CAPITAL LETTER R */
  _XXXXXXX,________,
  _XXXXXXX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX__XX,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,________,
  _XXX__XX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX____,XXX_____,
  _XXX____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0053[ 26] = { /* code 0053, LATIN CAPITAL LETTER S */
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX____,X_______,
  _XXX____,________,
  _XXXX___,________,
  __XXXXX_,________,
  ___XXXXX,X_______,
  _____XXX,XX______,
  _______X,XX______,
  _______X,XX______,
  _XX___XX,XX______,
  _XXXXXXX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0054[ 26] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0055[ 26] = { /* code 0055, LATIN CAPITAL LETTER U */
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXX___,XXX_____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0056[ 26] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXX____,__XX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  __XXX___,XXX_____,
  __XXX___,XXX_____,
  __XXX___,XX______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXX_X,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  _____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0057[ 39] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXX_____,XXX_____,XXX_____,
  _XXX____,XXX____X,XX______,
  _XXX____,XXXX___X,XX______,
  _XXX___X,XXXX___X,XX______,
  _XXX___X,X_XX___X,XX______,
  __XXX__X,X_XX___X,X_______,
  __XXX__X,X_XXX_XX,X_______,
  __XXX_XX,X_XXX_XX,X_______,
  __XXX_XX,___XX_XX,________,
  ___XX_XX,___XX_XX,________,
  ___XXXXX,___XXXXX,________,
  ___XXXXX,___XXXXX,________,
  ____XXX_,____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0058[ 26] = { /* code 0058, LATIN CAPITAL LETTER X */
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XX_XX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ___XXXXX,________,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_0059[ 26] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXX_____,XXX_____,
  XXXX____,XXX_____,
  _XXX___X,XX______,
  _XXXX__X,XX______,
  __XXX_XX,X_______,
  ___XX_XX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_005A[ 26] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _______X,XX______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_13_Bold_005F[ 26] = { /* code 005F, LOW LINE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontCalibri_13_Bold_CharInfo[39] = {
   {   5,   5,  1, acGUI_FontCalibri_13_Bold_0020 } /* code 0020 */
  ,{  15,  15,  2, acGUI_FontCalibri_13_Bold_0025 } /* code 0025 */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0030 } /* code 0030 */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0031 } /* code 0031 */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0032 } /* code 0032 */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0033 } /* code 0033 */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0034 } /* code 0034 */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0035 } /* code 0035 */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0036 } /* code 0036 */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0037 } /* code 0037 */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0038 } /* code 0038 */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0039 } /* code 0039 */
  ,{  13,  13,  2, acGUI_FontCalibri_13_Bold_0041 } /* code 0041 */
  ,{  12,  12,  2, acGUI_FontCalibri_13_Bold_0042 } /* code 0042 */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0043 } /* code 0043 */
  ,{  13,  13,  2, acGUI_FontCalibri_13_Bold_0044 } /* code 0044 */
  ,{  10,  10,  2, acGUI_FontCalibri_13_Bold_0045 } /* code 0045 */
  ,{  10,  10,  2, acGUI_FontCalibri_13_Bold_0046 } /* code 0046 */
  ,{  13,  13,  2, acGUI_FontCalibri_13_Bold_0047 } /* code 0047 */
  ,{  13,  13,  2, acGUI_FontCalibri_13_Bold_0048 } /* code 0048 */
  ,{   6,   6,  1, acGUI_FontCalibri_13_Bold_0049 } /* code 0049 */
  ,{   7,   7,  1, acGUI_FontCalibri_13_Bold_004A } /* code 004A */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_004B } /* code 004B */
  ,{   9,   9,  2, acGUI_FontCalibri_13_Bold_004C } /* code 004C */
  ,{  18,  18,  3, acGUI_FontCalibri_13_Bold_004D } /* code 004D */
  ,{  14,  14,  2, acGUI_FontCalibri_13_Bold_004E } /* code 004E */
  ,{  14,  14,  2, acGUI_FontCalibri_13_Bold_004F } /* code 004F */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0050 } /* code 0050 */
  ,{  14,  14,  2, acGUI_FontCalibri_13_Bold_0051 } /* code 0051 */
  ,{  12,  12,  2, acGUI_FontCalibri_13_Bold_0052 } /* code 0052 */
  ,{  10,  10,  2, acGUI_FontCalibri_13_Bold_0053 } /* code 0053 */
  ,{  10,  10,  2, acGUI_FontCalibri_13_Bold_0054 } /* code 0054 */
  ,{  14,  14,  2, acGUI_FontCalibri_13_Bold_0055 } /* code 0055 */
  ,{  12,  12,  2, acGUI_FontCalibri_13_Bold_0056 } /* code 0056 */
  ,{  19,  19,  3, acGUI_FontCalibri_13_Bold_0057 } /* code 0057 */
  ,{  12,  12,  2, acGUI_FontCalibri_13_Bold_0058 } /* code 0058 */
  ,{  11,  11,  2, acGUI_FontCalibri_13_Bold_0059 } /* code 0059 */
  ,{  10,  10,  2, acGUI_FontCalibri_13_Bold_005A } /* code 005A */
  ,{  10,  10,  2, acGUI_FontCalibri_13_Bold_005F } /* code 005F */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_13_Bold_Prop5 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontCalibri_13_Bold_CharInfo[ 38] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_13_Bold_Prop4 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontCalibri_13_Bold_CharInfo[ 12] /* address of first character */
  ,&GUI_FontCalibri_13_Bold_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_13_Bold_Prop3 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontCalibri_13_Bold_CharInfo[  2] /* address of first character */
  ,&GUI_FontCalibri_13_Bold_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_13_Bold_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontCalibri_13_Bold_CharInfo[  1] /* address of first character */
  ,&GUI_FontCalibri_13_Bold_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_13_Bold_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontCalibri_13_Bold_CharInfo[  0] /* address of first character */
  ,&GUI_FontCalibri_13_Bold_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCalibri_13_Bold = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,13 /* height of font  */
  ,13 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCalibri_13_Bold_Prop1}
  ,13 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

