/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Calibri_18_bold.c                                     *
* Font:        Calibri                                               *
* Height:      18                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  18                                           *
* Range disabled:       0000 - FFFF                                  *
* Character disabled:  0x40 (64)                                     *
* Character disabled:  0x5B (91)                                     *
* Character disabled:  0x5C (92)                                     *
* Character enabled:   0x5C (92)                                     *
* Character disabled:  0x5C (92)                                     *
* Character disabled:  0x5D (93)                                     *
* Character disabled:  0x5E (94)                                     *
* Character enabled:   0x5E (94)                                     *
* Character disabled:  0x5E (94)                                     *
* Character disabled:  0x5F (95)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCalibri_18_bold;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0041[ 36] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXX__,________,
  ___XXX__,________,
  __XX_XX_,________,
  __XX_XX_,________,
  _XX___XX,________,
  _XX___XX,________,
  _XXXXXXX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0042[ 18] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0043[ 18] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XXXX_,
  __XX___X,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX___X,
  ___XXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0044[ 36] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXX__,________,
  _XX__XX_,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX__XX_,________,
  _XXXXX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0045[ 18] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXX__,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0046[ 18] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXX__,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0047[ 36] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XX____,X_______,
  _XX_____,________,
  _XX_____,________,
  _XX__XXX,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX___X,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0048[ 36] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XXXXXXX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0049[ 18] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_004A[ 18] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_004B[ 18] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX___XX,
  _XX__XX_,
  _XX__XX_,
  _XX_XX__,
  _XXXX___,
  _XX_XX__,
  _XX__XX_,
  _XX__XX_,
  _XX___XX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_004C[ 18] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_004D[ 36] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXX___,XXXX____,
  _XX_X___,X_XX____,
  _XX_XX_X,X_XX____,
  _XX_XX_X,X_XX____,
  _XX__X_X,__XX____,
  _XX__XXX,__XX____,
  _XX__XXX,__XX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_004E[ 36] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX____X,X_______,
  _XXX___X,X_______,
  _XXXX__X,X_______,
  _XX_X__X,X_______,
  _XX_XX_X,X_______,
  _XX__X_X,X_______,
  _XX__XXX,X_______,
  _XX___XX,X_______,
  _XX____X,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_004F[ 36] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0050[ 18] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0051[ 36] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  ___XXXXX,________,
  _______X,X_______,
  ________,XX______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0052[ 18] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  _XX_XX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0053[ 18] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _XX__X__,
  _XX_____,
  _XXX____,
  __XXX___,
  ___XXX__,
  ____XX__,
  _X__XX__,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0054[ 18] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0055[ 36] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0056[ 36] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0057[ 36] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX___XXX,X___XX__,
  _XX__XXX,X__XX___,
  _XX_XX__,XX_XX___,
  _XX_XX__,XX_XX___,
  __XXX___,_XXX____,
  __XXX___,_XXX____,
  __XX____,__XX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0058[ 18] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX____XX,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ___XX___,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  XX____XX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_0059[ 18] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX____XX,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  __XXXX__,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCalibri_18_bold_005A[ 18] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  _____XX_,
  ____XX__,
  ___XX___,
  ___XX___,
  __XX____,
  _XX_____,
  XX______,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontCalibri_18_bold_CharInfo[26] = {
   {   9,   9,  2, acGUI_FontCalibri_18_bold_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_FontCalibri_18_bold_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_FontCalibri_18_bold_0043 } /* code 0043 */
  ,{   9,   9,  2, acGUI_FontCalibri_18_bold_0044 } /* code 0044 */
  ,{   7,   7,  1, acGUI_FontCalibri_18_bold_0045 } /* code 0045 */
  ,{   7,   7,  1, acGUI_FontCalibri_18_bold_0046 } /* code 0046 */
  ,{  10,  10,  2, acGUI_FontCalibri_18_bold_0047 } /* code 0047 */
  ,{   9,   9,  2, acGUI_FontCalibri_18_bold_0048 } /* code 0048 */
  ,{   4,   4,  1, acGUI_FontCalibri_18_bold_0049 } /* code 0049 */
  ,{   5,   5,  1, acGUI_FontCalibri_18_bold_004A } /* code 004A */
  ,{   8,   8,  1, acGUI_FontCalibri_18_bold_004B } /* code 004B */
  ,{   6,   6,  1, acGUI_FontCalibri_18_bold_004C } /* code 004C */
  ,{  13,  13,  2, acGUI_FontCalibri_18_bold_004D } /* code 004D */
  ,{  10,  10,  2, acGUI_FontCalibri_18_bold_004E } /* code 004E */
  ,{  10,  10,  2, acGUI_FontCalibri_18_bold_004F } /* code 004F */
  ,{   8,   8,  1, acGUI_FontCalibri_18_bold_0050 } /* code 0050 */
  ,{  10,  10,  2, acGUI_FontCalibri_18_bold_0051 } /* code 0051 */
  ,{   8,   8,  1, acGUI_FontCalibri_18_bold_0052 } /* code 0052 */
  ,{   7,   7,  1, acGUI_FontCalibri_18_bold_0053 } /* code 0053 */
  ,{   7,   7,  1, acGUI_FontCalibri_18_bold_0054 } /* code 0054 */
  ,{  10,  10,  2, acGUI_FontCalibri_18_bold_0055 } /* code 0055 */
  ,{   9,   9,  2, acGUI_FontCalibri_18_bold_0056 } /* code 0056 */
  ,{  14,  14,  2, acGUI_FontCalibri_18_bold_0057 } /* code 0057 */
  ,{   8,   8,  1, acGUI_FontCalibri_18_bold_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_FontCalibri_18_bold_0059 } /* code 0059 */
  ,{   7,   7,  1, acGUI_FontCalibri_18_bold_005A } /* code 005A */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCalibri_18_bold_Prop1 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontCalibri_18_bold_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCalibri_18_bold = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,18 /* height of font  */
  ,18 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCalibri_18_bold_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,9 /* Height of capital characters */
};

